# This is the simplest Instance Set with just one env/instance.
apiVersion: graybox.anthosapis.com/v1alpha1
kind: InstanceSet
metadata:
  name: orderentry-iset
spec:
  appProperties:
    name: changeMe
    envs:
      - name: "dev"
      - name: "test"
        includeInReleasePipeline: true
        releasePipelinePreviousEnvironmentDelay: 168h
      - name: "prod"
    tier: Development
    growthProfile: "Transactional"
    upgradePolicy: "Manual"
    # manintenanceWindows:
    # upgradeSoakingSchedule:
    # slo:
  # instanceTopologies:
  # - spec:
  #     fleetInstanceName:
  #     env:
  # - spec:
  #     fleetInstanceName:
  #     env:
