# This is the simplest Instance Set with just one env/instance.
apiVersion: graybox.anthosapis.com/v1alpha1
kind: InstanceSet
metadata:
  name: orderentry-iset03
spec:
  appProperties:
    name: changeMe
    envs:
    - Dev
    - Test
    - Staging
    - Prod
    tier: Development
    growthProfile: "Transactional"
    upgradePolicy: "Manual"
    # manintenanceWindows:
    # upgradeSoakingSchedule:
    # slo:
  # instanceTopologies:
  # - spec:
  #     fleetInstanceName:
  #     env:
  # - spec:
  #     fleetInstanceName:
  #     env:
