# This is the simplest Instance Set with just one env/instance.
apiVersion: graybox.anthosapis.com/v1alpha1
kind: InstanceSet
metadata:
  name: orderentry-iset02
  namespace: "<your-ns-fleet>" # {"$kpt-set":"namespace-fleet"}
spec:
  appProperties:
    name: "<your-app>" # {"$kpt-set":"app"}
    envs: # {"$kpt-set":"envs"}
    - "<your-envs>"
    tier: "<your-tier>" # {"$kpt-set":"tier"}
    growthProfile: "Transactional"
    upgradePolicy: "Manual"
    # manintenanceWindows:
    # upgradeSoakingSchedule:
    # slo:
  # instanceTopologies:
  # - spec:
  #     fleetInstanceName:
  #     env:
  # - spec:
  #     fleetInstanceName:
  #     env:
